### ISSUE TITLE
BCU 1 & 2: error: 'userRamStart' was not declared in this scope 

### ISSUE THREAD

**Issue by olterion** [selfbus/software-arm-lib#15]
Die Kompilierung der sblib für die BCU und BCU2 Debug Konfiguration ist nicht mehr möglich.
Es fehlen die Zeilen
```
extern int userRamStart;
#   define USER_RAM_START_DEFAULT 0x5FC
```
in der Daei bcu_type.h für die BCU 1 und BCU 2.

**Comment by StefanTT** [comment]
@FlorianVoelzke hat Du Zeit darauf einen Blick zu werfen?

**Comment by FlorianVoelzke** [comment]
Ich bin dran

**Comment by StefanTT** [comment]
:+1:
