### ISSUE TITLE
SPI Port 0 Fehler

### ISSUE THREAD

**Issue by olterion** [selfbus/software-arm-lib#16]
Ich hatte bereits im Forum einen Beitrag verfasst.
In der Datei spi.cpp muss die Zeile 70 verändert werden
```
Alt: LPC_SYSCON->PRESETCTRL |= portNum * 4;
Neu: LPC_SYSCON->PRESETCTRL |= (1 << (portNum * 2));
```
Somit wird bei port = 0 nicht mehr 0 ins PRESETCTRL Register geschrieben, sondern 1.

**Comment by StefanTT** [comment]
Ich hab' irgendwie ein Dejavu. Ich glaube den Fehler hat es an anderer Stelle auch schon gegeben ;-)
Wenn Du Lust hast dann kannst du gerne einen Pull Request für die Lib machen mit der Korrektur.

**Comment by StefanTT** [comment]
Fixed by commit 7c5011b
