### ISSUE TITLE
APCI_MEMORY_WRITE_PDU not handled correctly in void BCU::processDirectTelegram(int apci) / bcu.cpp

### ISSUE THREAD

**Issue by Darthyson** [selfbus/software-arm-lib#23]
Bug mentioned by Florian in the [selfbus-forum](https://selfbus.org/forum/viewtopic.php?p=4427&sid=c798c510f79c1203955267aae54931cd#p4427):
In case message APCI_MEMORY_WRITE_PDU wants to write across the memory border (address 0x4AFF ??) between userEeprom and memMapper it fails. I think his work-around was to create [MemMapperMod.h](actuators/outputs/out-cs-bim112/inc/MemMapperMod.h).
The same probably applies to message APCI_MEMORY_READ_PDU.

**Comment by FlorianVoelzke** [comment]
done
