### ISSUE TITLE
calling Bus::maxSendTries(0) leads to not sending telegrams at all

### ISSUE THREAD

**Issue by Darthyson** [selfbus/software-arm-lib#65]
this probably also affects `Bus::maxSendBusyTries(0)`
some logging data:
```
TLayer4::_begin debugging active
DUMP_TELEGRAMS Bus telegram dump enabled.
Bus begin - Timer prescaler: 000047 ttimer prescaler: 000047 ttimer value: 000882
nak retries: 000003 busy retries: 000003 phy addr: 10.15.254 (0xAFFE)
BCU Name: BIM112  MaskVersion: 0x0701
userRam    start: 0x05FC end: 0x0902 size: 0x0307
userEeprom start: 0x3F00 end: 0x4AFF size: 0x0C00 flashSize: 0x1000

QUE: (01007530) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
QUE: (01014449) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
QUE: (01021342) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
QUE: (01028208) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
QUE: (01035048) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
QUE: (01041862) B0 AF FE AF FD 6F 42 4D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C
```

**Comment by dallmair** [comment]
Calling `Bus::maxSendTries(0)` specifies that zero tries are allowed, in other words it means that no communication is allowed. So to me it seems the lib already behaves as expected.

What is the behavior you expect? I can come up with the following options:
1. Ignore the call when invalid values are passed.
2. Apply the default value instead of zero.
3. Fail hard.

Others?

**Comment by Darthyson** [comment]
`Bus::maxSendTries(0)` queues the telegram, but never sends or deletes it => 0 in telegrams in total
`Bus::maxSendTries(1)` sends the telegram and 1 repeated => 2 telegrams in total
`Bus::maxSendTries(2)` sends the telegram and 2 repeated => 3 telegrams in total
`Bus::maxSendTries(3)` sends the telegram and 3 repeated => 4 telegrams in total
So i think it better should be renamed to Bus::maxSendRetries()
